PVAO.Web/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using PVAOWeb.Helpers;
using PVAOWeb.Models;

namespace PVAOWeb.Controllers
{
    public class PageController : BaseController
    {
        [HttpPost]
        public ActionResult GetPages(int currentPage, string searchText)
        {
            var pageSize = int.Parse(ConfigurationManager.AppSettings["PageSize"].ToString());

            using (PVAOEntities _dbContext = new PVAOEntities())
            {
                var actualResult = _dbContext.Pages.Where(w => w.UrlPath != "/").OrderByDescending(x => x.Id).ToList();

                if (!string.IsNullOrEmpty(searchText))
                    actualResult = actualResult.Where(x => x.PageName.ToLower().Contains(searchText.ToLower())).ToList();

                var result = actualResult.OrderByDescending(x => x.Id).Skip((currentPage - 1) * pageSize).Take(pageSize).ToList();

                var pager = new Pager(actualResult.Count(), currentPage, pageSize, 6);

                List<object> pages = new List<object>();

                foreach (var item in result)
                {
                    var data = new
                    {
                        id = item.Id,
                        pageName = item.PageName,
                        description = item.Description,
                        urlPath = item.UrlPath,
                        icon = item.Icon,
                        status = item.Active ? "Active" : "Inactive",
                        dateCreated = item.DateCreated.ToString()
                    };

                    pages.Add(data);
                }

                return Json(new { pages, pager }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult GetPage(int id)
        {
            using (PVAOEntities _dbContext = new PVAOEntities())
            {
                _dbContext.Configuration.ProxyCreationEnabled = false;

                var result = _dbContext.Pages.Where(x => x.Id == id).ToList();

                List<object> pages = new List<object>();

                foreach (var item in result)
                {
                    var data = new
                    {
                        id = item.Id,
                        pageName = item.PageName,
                        description = item.Description,
                        urlPath = item.UrlPath,
                        accessibleByAll = item.AccessibleByAll,
                        active = item.Active
                    };

                    pages.Add(data);
                }

                return Json(pages, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult SaveChanges(int id, string pageName, string description, string urlPath, bool accessibleByAll = false, bool active = false)
        {
            try
            {
                using (PVAOEntities _dbContext = new PVAOEntities())
                {
                    _dbContext.Configuration.ProxyCreationEnabled = false;

                    var page = _dbContext.Pages.Single(x => x.Id == id);

                    if (page != null)
                    {
                        page.PageName = pageName;
                        page.Description = description;
                        page.UrlPath = urlPath;
                        page.AccessibleByAll = accessibleByAll;
                        page.Active = active;
                        _dbContext.SaveChanges();
                    }

                    return Json(page, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(string.Format("Error occurred. Error details: {0}", ex.Message));
            }
        }

        [HttpPost]
        public ActionResult GetPageAccess(int pageId, string searchText)
        {
            using (PVAOEntities _dbContext = new PVAOEntities())
            {
                var actualResult = (from pac in _dbContext.PageAccesses
                                   where pac.PageId == pageId
                                   join rol in _dbContext.Roles on pac.RoleId equals rol.Id
                                   select new
                                   {
                                       pac.Id,
                                       pac.RoleId,
                                       rol.RoleName,
                                       pac.CanCreate,
                                       pac.CanRead,
                                       pac.CanUpdate,
                                       pac.CanDelete
                                   }).ToList();

                if (!string.IsNullOrEmpty(searchText))
                    actualResult = actualResult.Where(x => x.RoleName.ToLower().Contains(searchText.ToLower())).ToList();

                List<object> pageAccess = new List<object>();

                foreach (var item in actualResult)
                {
                    var data = new
                    {
                        id = item.Id,
                        roleId = item.RoleId,
                        roleName = item.RoleName,
                        canCreate = item.CanCreate,
                        canRead = item.CanRead,
                        canUpdate = item.CanUpdate,
                        canDelete = item.CanDelete
                    };

                    pageAccess.Add(data);
                }

                return Json(new { pageAccess }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult GetRoles(int currentPage, int[] addedRoles, string searchText)
        {
            var pageSize = int.Parse(ConfigurationManager.AppSettings["PageSize"].ToString());

            using (PVAOEntities _dbContext = new PVAOEntities())
            {
                var actualResult = _dbContext.Roles.ToList();

                if (!string.IsNullOrEmpty(searchText))
                    actualResult = actualResult.Where(x => x.RoleName.ToLower().Contains(searchText.ToLower()) || x.Description.ToLower().Contains(searchText.ToLower())).ToList();

                var result = actualResult.OrderByDescending(x => x.Id).Skip((currentPage - 1) * pageSize).Take(pageSize).ToList();

                var pager = new Pager(actualResult.Count(), currentPage, pageSize, 6);

                List<object> roles = new List<object>();

                foreach (var item in result)
                {
                    var data = new
                    {
                        id = item.Id,
                        roleName = item.RoleName,
                        description = item.Description,
                        status = addedRoles != null ? addedRoles.Contains(item.Id) ? 1 : 0 : 0
                    };

                    roles.Add(data);
                }

                return Json(new { roles, pager }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult RemovePageAccess(int pageId, int[] ids)
        {
            try
            {
                using (PVAOEntities _dbContext = new PVAOEntities())
                {
                    var pageAccess = _dbContext.PageAccesses.Where(x => x.PageId == pageId && !ids.Contains(x.Id)).ToList();

                    if (pageAccess != null)
                    {
                        _dbContext.PageAccesses.RemoveRange(pageAccess);
                        _dbContext.SaveChanges();
                    }

                    return Json(pageAccess, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(string.Format("Error occurred. Error details: {0}", ex.Message));
            }
        }

        [HttpPost]
        public ActionResult SavePageAccess(int pageAccessId, int pageId, int roleId, bool canCreate = false, bool canRead = false, bool canUpdate = false, bool canDelete = false)
        {
            try
            {
                using (PVAOEntities _dbContext = new PVAOEntities())
                {
                    _dbContext.Configuration.ProxyCreationEnabled = false;

                    if (pageAccessId != 0)
                    {
                        var pageAccess = _dbContext.PageAccesses.Single(x => x.Id == pageAccessId);

                        if (pageAccess != null)
                        {
                            pageAccess.CanCreate = canCreate;
                            pageAccess.CanRead = canRead;
                            pageAccess.CanUpdate = canUpdate;
                            pageAccess.CanDelete = canDelete;
                            pageAccess.UpdatedBy = (int)Session["UserID"];
                            pageAccess.DateUpdated = DateTime.Now;
                            _dbContext.SaveChanges();
                        }

                        return Json(pageAccess, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        PageAccess pageAccess = new PageAccess()
                        {
                            PageId = pageId,
                            RoleId = roleId,
                            CanCreate = canCreate,
                            CanRead = canRead,
                            CanUpdate = canUpdate,
                            CanDelete = canDelete,
                            CreatedBy = (int)Session["UserID"],
                            DateCreated = DateTime.Now
                        };
                        _dbContext.PageAccesses.Add(pageAccess);
                        _dbContext.SaveChanges();

                        return Json(pageAccess, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            catch (Exception ex)
            {

PVAO.Web/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using PVAOWeb.Helpers;
using PVAOWeb.Models;

namespace PVAOWeb.Controllers
{
    public class RoleController : BaseController
    {
        [HttpPost]
        public ActionResult GetRoles(int currentPage, string searchText)
        {
            var pageSize = int.Parse(ConfigurationManager.AppSettings["PageSize"]);

            using (PVAOEntities _dbContext = new PVAOEntities())
            {
                var actualResult = _dbContext.Roles.OrderByDescending(x => x.Id).ToList();

                if (!string.IsNullOrEmpty(searchText))
                    actualResult = actualResult.Where(x => x.RoleName.ToLower().Contains(searchText.ToLower())).ToList();

                var result = actualResult.OrderByDescending(x => x.Id).Skip((currentPage - 1) * pageSize).Take(pageSize).ToList();

                var pager = new Pager(actualResult.Count(), currentPage, pageSize, 6);

                List<object> roles = new List<object>();

                foreach (var item in result)
                {
                    var user = _dbContext.Users.FirstOrDefault(x => x.Id == item.CreatedBy);

                    var data = new
                    {
                        id = item.Id,
                        roleName = item.RoleName,
                        description = item.Description,
                        createdBy = string.Format("{0} {1}", user.FirstName, user.LastName),
                        dateCreated = item.DateCreated.ToString()
                    };

                    roles.Add(data);
                }

                return Json(new { roles, pager }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult GetRole(int id)
        {
            using (PVAOEntities _dbContext = new PVAOEntities())
            {
                _dbContext.Configuration.ProxyCreationEnabled = false;

                var result = _dbContext.Roles.Where(x => x.Id == id).ToList();

                List<object> roles = new List<object>();

                foreach (var item in result)
                {
                    var createdBy = _dbContext.Users.FirstOrDefault(x => x.Id == item.CreatedBy);
                    string updatedBy = "n/a";
                    string dateUpdated = "n/a";

                    if (item.UpdatedBy != null)
                    {
                        var user = _dbContext.Users.FirstOrDefault(x => x.Id == item.UpdatedBy);

                        updatedBy = string.Format("{0} {1}", user.FirstName, user.LastName);
                        dateUpdated = item.DateUpdated.ToString();
                    }

                    var data = new
                    {
                        id = item.Id,
                        roleName = item.RoleName,
                        description = item.Description,
                        createdBy = string.Format("{0} {1}", createdBy.FirstName, createdBy.LastName),
                        dateCreated = item.DateCreated.ToString(),
                        updatedBy = updatedBy,
                        dateUpdated = dateUpdated
                    };

                    roles.Add(data);
                }

                return Json(roles, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult SaveChanges(int id, string roleName, string description)
        {
            try
            {
                using (PVAOEntities _dbContext = new PVAOEntities())
                {
                    _dbContext.Configuration.ProxyCreationEnabled = false;

                    if (id != 0)
                    {
                        var role = _dbContext.Roles.Single(x => x.Id == id);

                        if (role != null)
                        {
                            role.RoleName = roleName;
                            role.Description = description;
                            role.UpdatedBy = (int)Session["UserID"];
                            role.DateUpdated = DateTime.Now;
                            _dbContext.SaveChanges();
                        }

                        return Json(role, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        Role role = new Role()
                        {
                            RoleName = roleName,
                            Description = description,
                            CreatedBy = (int)Session["UserID"],
                            DateCreated = DateTime.Now
                        };
                        _dbContext.Roles.Add(role);
                        _dbContext.SaveChanges();

                        return Json(role, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            catch (Exception ex)
            {
                return Json(string.Format("Error occurred. Error details: {0}", ex.Message));
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                using (PVAOEntities _dbContext = new PVAOEntities())
                {
                    _dbContext.Configuration.ProxyCreationEnabled = false;

                    int deletionStatus = (int)ResponseStatusEnum.Success;

                    var role = _dbContext.Roles.SingleOrDefault(x => x.Id == id);

                    if (role != null)
                    {
                        if (_dbContext.UserRoles.Where(x => x.RoleId == id).Count() > 0)
                        {
                            deletionStatus = (int)ResponseStatusEnum.InUsed;
                        }
                        else
                        {
                            if (role != null)
                            {
                                _dbContext.Roles.Remove(role);
                                _dbContext.SaveChanges();
                            }
                        }
                    }
                    else
                        deletionStatus = (int)ResponseStatusEnum.Failed;

                    return Json(deletionStatus, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(string.Format("Error occurred. Error details: {0}", ex.Message));
            }
        }
    }
}

PVAO.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Metas -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Philippine Veterans Affairs Office" />
    <!-- Links -->
    <link rel="icon" type="image/png" href="#" />
    <title>@ViewBag.Title - PVAO Web Portal</title>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    <!-- google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">
    <script src="~/Scripts/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="~/Scripts/moment.min.js" crossorigin="anonymous"></script>
    <script src="~/Scripts/jspdf.debug.js"></script>

    <link href="~/Content/css/preloader.css" rel="stylesheet" />

    @*@Styles.Render("~/Content/css")*@
    @*@Scripts.Render("~/bundles/modernizr")*@

    <link href="~/Content/css/perfect-scrollbar.css" rel="stylesheet">
    <link href="~/Content/css/plugin.css" rel="stylesheet">
    <link href="~/Content/css/style.css" rel="stylesheet">
    <link href="~/Content/css/dashboard.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/paginationjs/2.1.4/pagination.css" />

    @*<link href="~/Content/css/pagination.css" rel="stylesheet">*@

    <script type="text/javascript">
        function dropdownAction(event, parent) {
            $(`#${parent}`).attr('data-id', $(`#${event.id}`).attr('data-id'));
            $(`#${parent}`).attr('data-description', $(`#${event.id}`).attr('data-description'));

            $(`#${parent}`).text($(`#${event.id}`).attr('data-description'));

            return false;
        }
    </script>
    @RenderSection("styles", false)
</head>
<body>
    <!--Preloader starts-->
    @*<div class="preloader js-preloader">
        <img src="~/Content/images/preloader.gif" alt="...">
    </div>*@
    <div id="page-loader">
        <div id="loader-logo"></div>
    </div>
    <div id="page-wrapper" class="page-wrapper" data-get-audit-logs-url="@Url.Action("GetAuditLogs", "AuditLog")" data-get-roles-url="@Url.Action("GetRoles", "Role")" data-get-pages-url="@Url.Action("GetPages", "Page")" data-get-users-url="@Url.Action("GetUsers", "User")" data-logout-user-url="@Url.Action("Logout", "Account")"
         data-get-current-user-url="@Url.Action("GetCurrentUser", "Account")" data-get-settings-url="@Url.Action("GetSettings", "Settings")" data-save-settings-url="@Url.Action("SaveChanges", "Settings")" data-save-audit-log-url="@Url.Action("SaveAuditLog", "AuditLog")" data-get-role-url="@Url.Action("GetRole", "Role")"
         data-save-role-url="@Url.Action("SaveChanges", "Role")" data-get-page-url="@Url.Action("GetPage", "Page")" data-get-page-access-url="@Url.Action("GetPageAccess", "Page")" data-get-page-roles-url="@Url.Action("GetRoles", "Page")" data-save-page-access-url="@Url.Action("SavePageAccess", "Page")"
         data-remove-page-access-url="@Url.Action("RemovePageAccess", "Page")" data-save-page-url="@Url.Action("SaveChanges", "Page")" data-get-user-url="@Url.Action("GetUser", "User")" data-save-user-url="@Url.Action("SaveChanges", "User")" data-get-user-roles-url="@Url.Action("GetUserRoles", "User")"
         data-remove-user-roles-url="@Url.Action("RemoveUserRoles", "User")" data-save-user-roles-url="@Url.Action("SaveUserRoles", "User")" data-get-dashboard-count-url="@Url.Action("GetDashboardCount", "Dashboard")" data-get-myprofile-url="@Url.Action("GetMyProfile", "User")" data-delete-role-url="@Url.Action("Delete", "Role")">
        <!--Sidebar Menu Starts-->
        <aside class="menu-sidebar js-right-sidebar d-block">
            <div class="logo">
                <a href="#">
                    <img src="@Url.Content("~/Content/images/logo-revise.png")" alt="Philippine Veterans Affairs Office" />
                </a>
            </div>
            @Html.Partial("_Navigation")
        </aside>
        <!--Sidebar Menu ends-->
        <!--Dashboard content Wrapper starts-->
        <div class="dash-content-wrap">
            <!-- Top header starts-->
            <header class="db-top-header">
                <div class="container-fluid">
                    <div class="row align-items-center">
                        <div class="col-md-8 col-sm-6 col-4">
                            <div class="site-navbar-wrap v2 style2">
                                <div class="site-navbar">
                                    <nav class="site-navigation">
                                        <div class="container">

                                        </div>
                                    </nav>
                                    <div class="d-lg-none sm-right">
                                        <a href="#" class="mobile-bar js-menu-toggle">
                                            <span class="lnr lnr-menu"></span>
                                        </a>
                                    </div>
                                    <!--mobile-menu starts -->
                                    <div class="site-mobile-menu">
                                        <div class="site-mobile-menu-header">
                                            <div class="site-mobile-menu-close  js-menu-toggle">
                                                <span class="lnr lnr-cross"></span>
                                            </div>
                                        </div>
                                        <div class="site-mobile-menu-body"></div>
                                    </div>
                                    <!--mobile-menu ends-->
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-6 col-8">
                            <div class="header-button">
                                @Html.Partial("_Notification")
                                <div class="header-button-item js-sidebar-btn">
                                    <img id="user-avatar-image">
                                    <span><span id="current-user"></span> <i class="ion-arrow-down-b"></i></span>
                                </div>
                                <div class="setting-menu js-right-sidebar d-none d-lg-block">
                                    <div class="account-dropdown__body">
                                        <div class="account-dropdown__item">
                                            <a href="/Administration/MyProfile/">
                                                <i class="fas fa-address-card"></i> My Profile
                                            </a>
                                        </div>
                                        <div class="account-dropdown__item">
                                            <a id="logout" href="">
                                                <i class="fas fa-sign-out-alt"></i> Logout
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Top header ends-->
            <div class="dash-content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
            <!--Dashboard footer starts-->
            <div class="dash-content spacer"></div>
            <footer class="footer fixed-bottom">
                Copyright © @DateTime.Now.Year <strong class="text-success font-weight-bold">Philippine Veterans Affairs Office (PVAO)</strong>. All Rights Reserved.
            </footer>
            <!--Dashboard footer ends-->
        </div>
        <!--Dashboard content Wrapper ends-->
    </div>

    @*@Scripts.Render("~/Scripts/jquery")*@

    <script src="~/Scripts/plugin.js" type="text/javascript"></script>
    <script src="~/Scripts/perfect-scrollbar.min.js" type="text/javascript"></script>
    <script src="~/Scripts/chart.js" type="text/javascript"></script>
    <script src="~/Scripts/main.js" type="text/javascript"></script>
    <script src="~/Scripts/dashboard.js" type="text/javascript"></script>
    <script src="~/Scripts/jspdf.plugin.autotable.js" type="text/javascript"></script>

    @RenderSection("scripts", required: false)

    @Scripts.Render("~/Scripts/layout")
</body>
</html>

PVAO.Web/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Metas -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Philippine Veterans Affairs Office" />
    <!-- Links -->
    <link rel="icon" type="image/png" href="#" />
    <title>Philippine Veterans Affairs Office (PVAO) | Web Portal</title>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    <!-- google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" crossorigin="anonymous"></script>
    <link href="~/Content/css/preloader.css" rel="stylesheet" />

    @*@Styles.Render("~/Content/css")*@
    @*@Scripts.Render("~/bundles/modernizr")*@

    <link href="~/Content/css/perfect-scrollbar.css" rel="stylesheet">
    <link href="~/Content/css/plugin.css" rel="stylesheet">
    <link href="~/Content/css/style.css" rel="stylesheet">
    <link href="~/Content/css/dashboard.css" rel="stylesheet">
</head>
<body>
    <div id="page-loader">
        <div id="loader-logo"></div>
    </div>
    <div id="page-wrapper">
        <!-- Top header ends-->

        <div class="dash-content">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!--Dashboard footer starts-->
        <div class="dash-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="copyright">
                            Copyright © @DateTime.Now.Year <strong class="text-success font-weight-bold">Philippine Veterans Affairs Office (PVAO)</strong>. All Rights Reserved.
                            <p class="text-muted">Material may not be published or reproduced in any form without prior written permission.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--Dashboard footer ends-->
    </div>

    @*@Scripts.Render("~/Scripts/jquery")*@

    <script src="~/Scripts/plugin.js" type="text/javascript"></script>
    <script src="~/Scripts/perfect-scrollbar.min.js" type="text/javascript"></script>
    <script src="~/Scripts/chart.js" type="text/javascript"></script>
    <script src="~/Scripts/main.js" type="text/javascript"></script>
    <script src="~/Scripts/dashboard.js" type="text/javascript"></script>

    @RenderSection("scripts", required: false)

    @Scripts.Render("~/Scripts/layout")
</body>
</html>

PVAO.Web/Views/Shared/_Navigation.cshtml
@using PVAOWeb.Models;

@using (PVAOEntities _dbContext = new PVAOEntities())
{
    if (Session["UserID"] != null)
    {
        int userId = (int)Session["UserID"];

        List<int> userRoles = _dbContext.UserRoles.Where(x => x.UserId == userId).Select(m => m.RoleId).ToList();

        List<int> pageAccess = _dbContext.PageAccesses.Where(x => userRoles.Contains(x.RoleId)).GroupBy(g => g.PageId).Select(m => m.Key).ToList();

        var subMenus = _dbContext.Pages.Where(x => pageAccess.Contains(x.Id) && x.Active).ToList();

        var parentMenus = subMenus.GroupBy(g => g.ParentMenu).Select(m => m.Key).ToList();

        var pages = subMenus.Union(_dbContext.Pages.Where(x => parentMenus.Contains(x.Id))).ToList();

        <div class="menu-sidebar__content js-scrollbar2">
            <nav class="navbar-sidebar2">
                @{
                    if (pages.Count() == 0)
                    {
                        <p class="text-center">--- You don't have access yet ---</p>
                    }
                }

            <ul class="list-unstyled navbar__list">
                @foreach (var item in pages.Where(x => parentMenus.Contains(x.Id)).OrderBy(x => x.Order).ToList())
                {
                    string controller = ViewContext.RouteData.Values["controller"].ToString().ToLower();
                    string action = ViewContext.RouteData.Values["action"].ToString().ToLower();
                    bool innerSubPage = !pages.Any(x => !x.IsParent && x.UrlPath?.ToLower().Trim() == ("/" + controller + "/" + action));

                    if (pages.Where(x => x.ParentMenu == @item.ParentMenu & !x.IsParent).Count() != 0)
                    {
                        string absolutePath = HttpContext.Current.Request.Url.AbsolutePath.Split('/')[1];
                        string jsArrow = absolutePath == item.PageName ? "js-arrow open" : "js-arrow";
                        string display = absolutePath == item.PageName ? "display: block;" : "display: none;";

                        <li class="has-sub">
                            <a class="@jsArrow" href="#">
                                <i class="@item.Icon"></i>@item.PageName
                            </a>
                            <ul class="list-unstyled navbar__sub-list js-sub-list" style="@display">
                                @foreach (var sub in pages.Where(x => x.ParentMenu == item.ParentMenu && !x.IsParent).ToList())
                                {
                                    bool active = (("/" + controller + "/" + action) == sub.UrlPath?.ToLower().Trim());
                                    <li>
                                        <a href="@sub.UrlPath" class="@(active ? "active" : "")">@sub.PageName</a>
                                    </li>
                                }
                            </ul>
                        </li>
                    }
                    else
                    {
                        bool active = (("/" + controller + "/" + action) == item.UrlPath?.ToLower().Trim()) || (innerSubPage && item.UrlPath?.ToLower().Trim() == ("/" + controller + "/index"));

                        <li>
                            <a href="@item.UrlPath" class="@(active ? "active" : "")">
                                <i class="@item.Icon"></i>@item.PageName
                            </a>
                        </li>
                    }
                }
            </ul>
            </nav>
        </div>
    }
}

PVAO.Web/Views/Shared/_Notification.cshtml
<div class="header-button-item has-noti js-item-menu">
    <i class="ion-ios-bell-outline"></i>
    <div class="notifi-dropdown js-dropdown">
    </div>
</div>