PVAO.Web/Controllers/OverRemittanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PVAOWebPortal.Controllers
{
    public class OverRemittanceController : Controller
    {
        // GET: OverRemittance
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            return View();
        }

        public ActionResult ForApproval()
        {
            return View();
        }

        public ActionResult Details()
        {
            return View();
        }
    }
}

PVAO.Web/Views/OverRemittance/Details.cshtml
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
    ViewBag.Title = "Over-remittance Details";
}

<div class="row">
    <div class="col-md-12">
        <div class="viewd-item-wrap popup-wrapper">
            <div class="details-header my-3 p-3 bg-body rounded shadow-sm">
                <div class="most-viewed-item">
                    <div class="most-viewed-img">
                        <a href="#"><img src="~/Content/images/header/money.png" width="200" height="200" alt="..."></a>
                    </div>
                    <div class="most-viewed-detail">
                        <h3 class="display-5 fw-normal">Over-remittance Details</h3>
                        <p id="benefit-status"></p>
                        <p id="vdms-number-name" class="list-address"></p>
                        <p id="status-claim-number"></p>
                    </div>
                </div>
            </div>
            <p class="breadcrumbs">
                <i class="fa fa-link"></i>
                <a href="/Dashboard/Index">Over-remittance List</a> / <span class="subheader-text">Over-remittance Details</span>
            </p>
            <br />
            <p><mark><i>All fields with red asterisk (*) are required to fill.</i></mark></p>
            <br />

            <div id="alert-div" class="alert alert-success alert-dismissible fade show invisible-element" role="alert">
                <strong><i class="fa fa-info-circle"></i> <span class="message">Total over-remittance amount has been successfully computed. You can now submit it for approval.</span> </strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <form>
                <div class="row">
                    <div class="col-md-6">
                        <h5 class="pb-2 details-section">Pensioner Information</h5>
                        <hr style="border-bottom: solid 1px; border-bottom-color: #009246" />

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Claim Number <span>*</span></label>
                                    <input id="claim-number-text" type="text" class="form-control" value="OBR-NCR-20-000004" readonly />
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>Benefit Status <span>*</span></label>
                                    <input id="benefit-status-text" type="text" class="form-control" readonly />
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>Pensioner Name <span>*</span></label>
                                    <input id="pensioner-name-text" type="text" class="form-control" readonly />
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Relation <span>*</span></label>
                                    <input id="relation-text" type="text" class="form-control" readonly />
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Address <span>*</span></label>
                            <input id="address-text" class="form-control" readonly />
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Mobile Number</label>
                                    <input id="mobile-number-text" type="text" class="form-control" readonly />
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Email Address <span>*</span></label>
                                    <input id="email-address-text" type="text" class="form-control" readonly />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h5 class="pb-2 details-section">Veteran Information</h5>
                        <hr style="border-bottom: solid 1px; border-bottom-color: #009246" />
                        <div class="form-group">
                            <label>VDMS Number <span>*</span></label>
                            <input id="vdms-number-text" type="text" class="form-control" readonly />
                        </div>
                        <div class="form-group">
                            <label>Veteran Name <span>*</span></label>
                            <input id="veteran-name-text" type="text" class="form-control" readonly />
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Date of Birth <span>*</span></label>
                                    <input id="birth-date-text" type="text" class="form-control" readonly />
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Age <span>*</span></label>
                                    <input id="age-text" type="text" class="form-control" readonly />
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Gender <span>*</span></label>
                                    <input id="gender-text" type="text" class="form-control" readonly />
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Date Of Death <span>*</span></label>
                                    <input id="date-death-text" type="text" class="form-control" readonly />
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Cause Of Death <span>*</span></label>
                                    <input id="cause-death-text" type="text" class="form-control" readonly />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <h5 class="pb-2 details-section">Bank Information</h5>
                        <hr style="border-bottom: solid 1px; border-bottom-color: #009246" />

                        <table id="pay-period-table" class="table table-hover"></table>

                        <div id="computed-amount-div" class="recent-activity invisible-element">
                            <ul class="act-wrap">
                                <li class="alert br-o fade show">
                                    <strong>Total Over-remittance Amount: </strong> <span id="total-overremittance-amount">0.00</span>
                                </li>
                            </ul>
                        </div>

                        <hr id="approved-rejected-line" class="dotted-line invisible-element">

                        <p id="approved-rejected-status"></p>
                        <p id="approved-rejected-by"></p>
                        <p id="date-approved-reject"></p>
                        <p id="reject-remarks"></p>

                        <hr class="dotted-line">

                        <button id="approve-btn" type="button" class="btn btn-success"><i class="far ion-thumbsup"></i> Approved</button>
                        <button id="reject-btn" type="button" class="btn btn-danger"><i class="far ion-thumbsdown"></i> Reject</button>
                        <button id="compute-btn" type="button" class="btn btn-primary"><i class="far ion-calculator"></i> Compute</button>
                        <button id="submit-approval-btn" type="button" class="btn btn-success"><i class="far ion-thumbsup"></i> Submit for Approval</button>
                        <button id="close-btn" type="button" class="btn btn-dark"><i class="far ion-close"></i> Close</button>

                        <br /><br />
                        <p class="text-dark">
                            <strong>Computed By:</strong> <span id="computed-by">n/a</span> &nbsp; <strong>Date Computed:</strong> <span id="date-computed">n/a</span> &nbsp;
                            <strong>Submitted By:</strong> <span id="submitted-by">n/a</span> &nbsp; <strong>Date Submitted:</strong> <span id="date-submitted">n/a</span>
                        </p>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="submit-confirmation-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <h3>Submit For Approval</h3>
                <p>Are you sure you want to submit this over-remittance for approval?</p>
                <br />
                <div class="clearfix">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>&nbsp;
                    <button type="button" class="btn btn-success submit-approval-btn">Yes, proceed</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="approve-confirmation-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <h3>Approve Over-remittance</h3>
                <p>Are you sure you want to approve this over-remittance? You can't undo this action once clicked.</p>
                <br />
                <div class="clearfix">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>&nbsp;
                    <button type="button" class="btn btn-success approve-btn">Yes, approve it</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="reject-reason-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Reject Over-remittance</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger reason-rejection-alert invisible-element" role="alert">
                    <strong><i class="lnr lnr-bookmark"></i> Reason for rejection is required.</strong>
                </div>

                <form id="upload_form" method="post">
                    <div class="form-group">
                        <label>Reason for Rejection <span>*</span></label>
                        <textarea id="reason-rejection-text" class="form-control" rows="3"></textarea>
                    </div>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>&nbsp;
                    <button type="button" class="btn btn-danger reject-btn">Yes, reject it</button>
                </form>
            </div>
        </div>
    </div>
</div>


@Scripts.Render("~/Scripts/overremittance")

PVAO.Web/Views/OverRemittance/ForApproval.cshtml
@{
    ViewBag.Title = "Over-remittance For Approval";
}
<div id="over-remittance-for-approval-list" class="recent-activity my-listing">
    <div class="act-title">
        <h5><span class="header-text"></span></h5>
        <p>For approval over-remittances for late termination of DW - Disability Pension (Surviving Spouse), DC - Disability Pension (minor) &<br /> TP - Death Pension (Parent).</p>

        <p class="breadcrumbs">
            <i class="fa fa-link"></i>
            <a href="/Dashboard/Index">Home</a> / <a href="/OverRemittance/Index">Over-remittance Option</a> / <span class="subheader-text">For Approval List</span>
        </p>
    </div>
    <div class="row">
        <form class="row hero__form v1 filter listing-filter list-filter">
            <div class="bs-dropdown dropdown show"></div>

            <div class="yr-dropdown dropdown show"></div>

            <div class="mt-dropdown dropdown show"></div>

            <div class="input-search">
                <input id="search-overremittance-text" type="text" placeholder="Search over-remittances here...">
            </div>
        </form>
        <div id="wrapper" class="col-md-12">
            <section>
                <div class="data-container" style="overflow-x:auto;">
                    <table id="overremittance-table" class="table table-hover"></table>
                    <center id="no-available-overremittances">
                        <p class="font-italic">
                            <i class="fa fa-exclamation-triangle error-icon" aria-hidden="true"></i> No over-remittances listed yet.
                        </p>
                    </center>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-7"></div>
                    <div class="col-md-5">
                        <button id="export-excel-button" type="button" class="btn btn-success"><i class="far fa-file-excel"></i> Export to Excel</button>
                        <button id="export-pdf-button" type="button" class="btn btn-danger"><i class="far fa-file-pdf"></i> Export to PDF</button>
                    </div>
                </div>
                <br /><br />
            </section>

            <div class="overremittance-pagination"></div>

        </div>
    </div>
</div>

@Scripts.Render("~/Scripts/layout")
@Scripts.Render("~/Scripts/overremittance/forapproval")
@Scripts.Render("~/Scripts/api")
@Scripts.Render("~/Scripts/excelhelper")
@Scripts.Render("~/Scripts/pdfhelper")

PVAO.Web/Views/OverRemittance/Index.cshtml
@{
    ViewBag.Title = "Over-remittance Options";
}
<div class="recent-activity">
    <div class="act-title">
        <h5>Over-remittance Option</h5>
        <p class="breadcrumbs">
            <i class="fa fa-link"></i>
            <a href="/Dashboard/Index">Dashboard</a> / <span class="subheader-text">Over-remittance Option</span>
        </p>

        <br />

        <div class="act-title greetings">
            <p class="text-center">Please select an option below to view either over-remittance or for approval list.</p>
        </div>
    </div>
</div>
<div id="over-remittance-index" class="statistic-wrap mt-60">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-6 col-md-6 col-12">
                <a href="@Url.Action("List", "OverRemittance")">
                    <div class="statistic__item item--red">
                        <h3 class="counter-value total-list">Over-remittance List (0)</h3>
                        <br />
                        <span class="desc">Over-remittance for late termination of DW, DC & TP.</span>
                        <div class="icon">
                            <img src="/Content/images/dashboard/home.png" alt="Over-remittance List">
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-xl-6 col-md-6 col-12">
                <a href="@Url.Action("ForApproval", "OverRemittance")">
                    <div class="statistic__item item--blue">
                        <h3 class="counter-value for-approval">For Approval List(0)</h3>
                        <br />
                        <span class="desc">Calculated over-remittance list for approval.</span>
                        <div class="icon">
                            <img src="/Content/images/dashboard/review.png" alt="For Approval List">
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

<div class="dash-content">
    <div class="container-fluid">
        <div class="row"></div>
    </div>
</div>

@Scripts.Render("~/Scripts/dashboard")

PVAO.Web/Views/OverRemittance/List.cshtml
@{
    ViewBag.Title = "Over-remittance List";
}
<div id="over-remittance-list" class="recent-activity my-listing">
    <div class="act-title">
        <h5><span class="header-text"></span></h5>
        <p>Over-remittances for late termination of DW - Disability Pension (Surviving Spouse), DC - Disability Pension (minor) &<br /> TP - Death Pension (Parent).</p>

        <p class="breadcrumbs">
            <i class="fa fa-link"></i>
            <a href="/Dashboard/Index">Home</a> / <a href="/OverRemittance/Index">Over-remittance Option</a> / <span class="subheader-text">Over-remittance List</span>
        </p>
    </div>
    <div class="row">
        <form class="row hero__form v1 filter listing-filter list-filter">
            <div class="bs-dropdown dropdown show"></div>

            <div class="yr-dropdown dropdown show"></div>

            <div class="mt-dropdown dropdown show"></div>

            <div class="input-search">
                <input id="search-overremittance-text" type="text" placeholder="Search over-remittances here...">
            </div>
        </form>
        <div id="wrapper" class="col-md-12">
            <section>
                <div class="data-container" style="overflow-x:auto;">
                    <table id="overremittance-table" class="table table-hover"></table>
                    <center id="no-available-overremittances">
                        <p class="font-italic">
                            <i class="fa fa-exclamation-triangle error-icon" aria-hidden="true"></i> No over-remittances listed yet.
                        </p>
                    </center>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-7"></div>
                    <div class="col-md-5">
                        <button id="export-excel-button" type="button" class="btn btn-success"><i class="far fa-file-excel"></i> Export to Excel</button>
                        <button id="export-pdf-button" type="button" class="btn btn-danger"><i class="far fa-file-pdf"></i> Export to PDF</button>
                    </div>
                </div>
                <br /><br />
            </section>

            <div class="overremittance-pagination"></div>

        </div>
    </div>
</div>

@Scripts.Render("~/Scripts/layout")
@Scripts.Render("~/Scripts/overremittance")
@Scripts.Render("~/Scripts/api")
@Scripts.Render("~/Scripts/excelhelper")
@Scripts.Render("~/Scripts/pdfhelper")