PVAO.Web/Controllers/AccruedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PVAOWeb.Controllers
{
    public class AccruedController : Controller
    {
        // GET: Accrued
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            return View();
        }

        public ActionResult ForApproval()
        {
            return View();
        }

        public ActionResult SOD()
        {
            return View();
        }

        public ActionResult Details()
        {
            return View();
        }

        public ActionResult AccruedInquiry()
        {
            return View();
        }
    }
}

PVAO.Web/Views/Accrued/AccruedInquiry.cshtml
@{
    ViewBag.Title = "Accrued Inquiry";
}
<div id="accrued-inquiry" class="recent-activity my-listing">
    <div class="act-title">
        <h2><span class="header-text">Accrued Inquiry</span></h2>
        <p class="breadcrumbs">
            <i class="fa fa-link"></i>
            <a href="/Dashboard/Index">Home</a> / <a href="/Accrued/Index">Accrued Option</a> / <span class="subheader-text">Accrued Inquiry</span>
        </p>
    </div>
    <div class="row">
        <form class="row hero__form v1 filter listing-filter list-filter">
            <div class="button">
                <a class="btn v3" href="#" data-toggle="modal" data-target="#pensioner-modal"><i class="fa fa-search-plus"></i> Choose Pensioners to process</a>
            </div>
            <div class="modal fade bd-example-modal-lg" id="pensioner-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Select pensioners</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <br />
                            <form id="upload_form" enctype="multipart/form-data" method="post">
                                <table id="beneficiary-list" class="table-bordered"></table>
                                <br />
                                <button id="beneficiary-ok-button" type="button" class="btn btn-primary"> Ok</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@Scripts.Render("~/Scripts/accrued")

PVAO.Web/Views/Accrued/Details.cshtml
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
    ViewBag.Title = "Over-remittance Details";
}
<div class="row">
    <div class="col-md-12">
        <div class="viewd-item-wrap popup-wrapper">
            <div class="details-header my-3 p-3 bg-body rounded shadow-sm">
                <div class="most-viewed-item">
                    <div class="most-viewed-img">
                        <a href="#"><img src="~/Content/images/header/money.png" width="200" height="200" alt="..."></a>
                    </div>
                    <div class="most-viewed-detail">
                        <h3 class="display-5 fw-normal">Over-remittance Details</h3>
                        <br />
                        <p id="vdms-number-name" class="list-address"></p>
                        <p id="status-claim-number"></p>
                    </div>
                </div>
            </div>
            <p class="breadcrumbs">
                <i class="fa fa-link"></i>
                <a href="/Dashboard/Index">Over-remittance List</a> / <span class="subheader-text">Over-remittance Details</span>
            </p>
            <br />
            <p><mark><i>All fields with red asterisk (*) are required to fill.</i></mark></p>
            <br />

            <form>
                <div class="row">
                    <div class="col-md-6">
                        <h5 class="pb-2 details-section">Beneficiary Information</h5>
                        <hr style="border-bottom: solid 1px; border-bottom-color: #009246" />
                        <div class="form-group">
                            <label>Claim Number <span>*</span></label>
                            <input id="claim-number-text" type="text" class="form-control" value="OBR-NCR-20-000004" readonly />
                        </div>
                        <div class="form-group">
                            <label>Beneficiary Name <span>*</span></label>
                            <input id="beneficiary-name-text" type="text" class="form-control" value="ESCODA, ANTONIO SR. DA" readonly />
                        </div>
                        <div class="form-group">
                            <label>Relation <span>*</span></label>
                            <input id="relation-text" type="text" class="form-control" value="SPOUSE" readonly />
                        </div>
                        <div class="form-group">
                            <label>Address <span>*</span></label>
                            <input id="address-text" class="form-control" value="66 E Abada St., Loyola Heights, Quezon City, 1302" readonly />
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Mobile Number</label>
                                    <input id="mobile-number-text" type="text" class="form-control" value="09064925352" readonly />
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Email Address <span>*</span></label>
                                    <input id="email-address-text" type="text" class="form-control" value="escoda.antonio_sr@yahoo.com" readonly />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h5 class="pb-2 details-section">Veteran Information</h5>
                        <hr style="border-bottom: solid 1px; border-bottom-color: #009246" />
                        <div class="form-group">
                            <label>VDMS Number <span>*</span></label>
                            <input id="vdms-number-text" type="text" class="form-control" value="09736" readonly />
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>Veteran Name <span>*</span></label>
                                    <input id="veteran-name-text" type="text" class="form-control" value="ESCODA, JOSEFINA LLANES" readonly />
                                </div>

                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Nationality <span>*</span></label>
                                    <input id="nationality-text" type="text" class="form-control" value="FILIPINO" readonly />
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>VFP Organization <span>*</span></label>
                            <input id="vfp-organization-text" type="text" class="form-control" value="Philippine Veterans Legion" readonly />
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Date of Birth <span>*</span></label>
                                    <input id="birth-date-text" type="text" class="form-control" value="09/20/1919" readonly />
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Age <span>*</span></label>
                                    <input id="age-text" type="text" class="form-control" value="101" readonly />
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Gender <span>*</span></label>
                                    <input id="gender-text" type="text" class="form-control" value="FEMALE" readonly />
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Date Of Death <span>*</span></label>
                                    <input id="date-death-text" type="text" class="form-control" value="12/15/2020" readonly />
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Cause Of Death <span>*</span></label>
                                    <input id="cause-death-text" type="text" class="form-control" value="Battle" readonly />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <h5 class="pb-2 details-section">Remittances (3)</h5><br />
                <p>Continuous pension remittances made to the account of even after the death of the veteran/pensioner.</p>
                <hr style="border-bottom: solid 1px; border-bottom-color: #009246" />

                <div class="row">
                    <div class="row hero__form v1 filter listing-filter detail-filter">
                        <div class="form-inline coverage-filter">
                            <label>Coverage :</label>
                        </div>
                        <div class="form-inline">
                            <label class="date-label">Date From</label>
                            <div class="form-group mb-2">
                                <label class="sr-only">Date From</label>
                            </div>
                            <div class="form-group mx-sm-3 mb-2">
                                <div id="datepicker-from" class="input-group date" data-date-format="dd-mm-yyyy">
                                    <input id="date-from-text" type="text" value="04/03/2021" class="form-control">
                                    <span class="input-group-addon"><i class="lnr lnr-calendar-full"></i></span>
                                </div>
                            </div>
                            <label class="date-label">Date To</label>
                            <div class="form-group mx-sm-3 mb-2">
                                <div id="datepicker-to" class="input-group date" data-date-format="dd-mm-yyyy">
                                    <input id="date-to-text" type="text" value="04/04/2021" class="form-control">
                                    <span class="input-group-addon"><i class="lnr lnr-calendar-full"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <table id="issued-check-table" class="table table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">Cheque Number</th>
                                    <th scope="col">Bank Code</th>
                                    <th scope="col">Bank Name</th>
                                    <th scope="col">Branch</th>
                                    <th scope="col">Date Issued</th>
                                    <th scope="col" class="text-right">Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="text-left">0001037401</td>
                                    <td class="text-left">AFP</td>
                                    <td class="text-left">AFP SAVINGS AND LOAN ASSN</td>
                                    <td class="text-left">BAGUIO CITY BRANCH</td>
                                    <td class="text-left">01/23/2021</td>
                                    <td class="text-right">2,500.00</td>
                                </tr>
                                <tr>
                                    <td class="text-left">0007276612</td>
                                    <td class="text-left">AUB</td>
                                    <td class="text-left">ASIA UNITED BANK</td>
                                    <td class="text-left">BINONDO BRANCH</td>
                                    <td class="text-left">02/01/2021</td>
                                    <td class="text-right">2,320.12</td>
                                </tr>
                                <tr>
                                    <td class="text-left">0007278721</td>
                                    <td class="text-left">DBP</td>
                                    <td class="text-left">DEVT BANK OF THE PHIL</td>
                                    <td class="text-left">BACOLOD BRANCH</td>
                                    <td class="text-left">02/06/2021</td>
                                    <td class="text-right">1,678.88</td>
                                </tr>
                            </tbody>
                            <tfoot>
                                <tr class="total-footer">
                                    <td class="right font-weight-bold" colspan="5">Total Amount : </td>
                                    <td class="right font-weight-bold">6,499.00</td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <button id="compute-btn" type="button" class="btn btn-primary"><i class="far ion-calculator"></i> Compute</button>
                            <button id="submit-approval-btn" type="button" class="btn btn-success"><i class="far ion-thumbsup"></i> Submit for Approval</button>
                            <button id="print-btn" type="button" class="btn btn-info"><i class="far ion-printer"></i> Print</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@Scripts.Render("~/Scripts/overremittance")

PVAO.Web/Views/Accrued/ForApproval.cshtml
<div id="remittance-approval" class="recent-activity my-listing">
    <div class="act-title">
        <h5><span class="header-text">Accrued For Approval (12)</span></h5>
        <p>Calculated accrued list for approval.</p>

        <p class="breadcrumbs">
            <i class="fa fa-link"></i>
            <a href="/Dashboard/Index">Home</a> / <a href="/Accrued/Index">Accrued Option</a> / <span class="subheader-text">Accrued for Approval</span>
        </p>
    </div>
    <div class="row">
        <form class="row hero__form v1 filter listing-filter list-filter">
            <div class="dropdown show">
                <a id="st-dropdown-action" class="btn btn-secondary dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    -- Status --
                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="width: 300px;">
                    <a id="st-all" data-id="0" data-description="-- Status --" class="dropdown-item" href="" onclick="return dropdownAction(this, 'st-dropdown-action');">-- Status --</a>
                    <a id="st-approved" data-id="1" data-description="Approved" class="dropdown-item" href="" onclick="return dropdownAction(this, 'st-dropdown-action');">Approved</a>
                    <a id="st-forapproval" data-id="2" data-description="For Approval" class="dropdown-item" href="" onclick="return dropdownAction(this, 'st-dropdown-action');">For Approval</a>
                    <a id="st-rejected" data-id="3" data-description="Rejected" class="dropdown-item" href="" onclick="return dropdownAction(this, 'st-dropdown-action');">Rejected</a>
                </div>
            </div>

            <div class="input-search">
                <input id="search-text" class="search-text" type="text" placeholder="Search Accrued for approval here...">
            </div>
        </form>
        <div id="wrapper" class="col-md-12">
            <section>
                <div class="data-container">
                    <table id="overremittance-forapproval-table" class="table table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">VDMS Number</th>
                                <th scope="col">Beneficiary Name</th>
                                <th scope="col">Age</th>
                                <th scope="col">Gender</th>
                                <th scope="col">Claim Number</th>
                                <th scope="col">Amount</th>
                                <th scope="col" class="text-center">Status</th>
                                <th scope="col" class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">09736</th>
                                <td>Sappari Guillizzoni</td>
                                <td>40</td>
                                <td>MALE</td>
                                <td>OV-MCO-13-001995</td>
                                <td>6,499.00</td>
                                <td class="text-center"><span class="badge badge-warning">For Approval</span></td>
                                <td>
                                    <button type="button" class="btn btn-primary"><i class="far fa-eye"></i> View</button>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">03778</th>
                                <td>Guillermo Button</td>
                                <td>38</td>
                                <td>MALE</td>
                                <td>OW-MCO-04-002377</td>
                                <td>1,997.00</td>
                                <td class="text-center"><span class="badge badge-warning">For Approval</span></td>
                                <td>
                                    <button type="button" class="btn btn-primary"><i class="far fa-eye"></i> View</button>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">16627</th>
                                <td>Mariah Maculangan</td>
                                <td>41</td>
                                <td>FEMALE</td>
                                <td>DA-MCO-12-062881</td>
                                <td>0.00</td>
                                <td class="text-center"><span class="badge badge-danger">Rejected</span></td>
                                <td>
                                    <button type="button" class="btn btn-primary"><i class="far fa-eye"></i> View</button>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">07361</th>
                                <td>Valerie Liberty</td>
                                <td>25</td>
                                <td>FEMALE</td>
                                <td>OV-MCO-23-066123</td>
                                <td>8,231.00</td>
                                <td class="text-center"><span class="badge badge-warning">For Approval</span></td>
                                <td>
                                    <button type="button" class="btn btn-primary"><i class="far fa-eye"></i> View</button>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">01524</th>
                                <td>Clas Mirano</td>
                                <td>21</td>
                                <td>MALE</td>
                                <td>OV-MCO-15-088123</td>
                                <td>2,199.00</td>
                                <td class="text-center"><span class="badge badge-warning">For Approval</span></td>
                                <td>
                                    <button type="button" class="btn btn-primary"><i class="far fa-eye"></i> View</button>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">09826</th>
                                <td>Aurora Valmores</td>
                                <td>43</td>
                                <td>FEMALE</td>
                                <td>OV-MCO-12-927616</td>
                                <td>40,530.00</td>
                                <td class="text-center"><span class="badge badge-warning">For Approval</span></td>
                                <td>
                                    <button type="button" class="btn btn-primary"><i class="far fa-eye"></i> View</button>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">04516</th>
                                <td>Flecitus Vitug</td>
                                <td>19</td>
                                <td>MALE</td>
                                <td>OV-MCO-15-078251</td>
                                <td>816.00</td>
                                <td class="text-center"><span class="badge badge-danger">Rejected</span></td>
                                <td>
                                    <button type="button" class="btn btn-primary"><i class="far fa-eye"></i> View</button>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">09271</th>
                                <td>Ernesto Torrado</td>
                                <td>14</td>
                                <td>MALE</td>
                                <td>OV-MCO-23-005241</td>
                                <td>8,231.00</td>
                                <td class="text-center"><span class="badge badge-danger">Rejected</span></td>
                                <td>
                                    <button type="button" class="btn btn-primary"><i class="far fa-eye"></i> View</button>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">03970</th>
                                <td>Rambunaian Mangingisa</td>
                                <td>32</td>
                                <td>MALE</td>
                                <td>OV-MCO-15-056178</td>
                                <td>3,401.00</td>
                                <td class="text-center"><span class="badge badge-success">Approved</span></td>
                                <td>
                                    <button type="button" class="btn btn-primary"><i class="far fa-eye"></i> View</button>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">05962</th>
                                <td>Sherwin Tesoro</td>
                                <td>16</td>
                                <td>MALE</td>
                                <td>OV-MCO-23-066123</td>
                                <td>3,412.00</td>
                                <td class="text-center"><span class="badge badge-success">Approved</span></td>
                                <td>
                                    <button type="button" class="btn btn-primary"><i class="far fa-eye"></i> View</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <div class="col-md-10"></div>
                    <div class="col-md-2">
                        <div id="pagination-overremittance-forapproval"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-7"></div>
                    <div class="col-md-5">
                        <button type="button" id="export-excel-forapproval-button" class="btn btn-success"><i class="far fa-file-excel"></i> Export to Excel</button>
                        <button type="button" id="export-pdf-forapproval-button" class="btn btn-danger"><i class="far fa-file-pdf"></i> Export to PDF</button>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

@Scripts.Render("~/Scripts/accrued")
@Scripts.Render("~/Scripts/excelhelper")
@Scripts.Render("~/Scripts/pdfhelper")

PVAO.Web/Views/Accrued/Index.cshtml
@{
    ViewBag.Title = "Accrued Options";
}
<div class="recent-activity">
    <div class="act-title">
        <h5>Accrued Option</h5>
        <p class="breadcrumbs">
            <i class="fa fa-link"></i>
            <a href="/Dashboard/Index">Dashboard</a> / <span class="subheader-text">Accrued Option</span>
        </p>

        <br />

        <div class="act-title greetings">
            <p class="text-center">Please select an option below to view either accrued, for approval list or create an SOD entry.</p>
        </div>
    </div>
</div>
<div class="statistic-wrap mt-60">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-4 col-md-6 col-12">
                <a href="@Url.Action("List", "Accrued")">
                    <div class="statistic__item item--red">
                        <h3 class="counter-value">Accrued List (25)</h3>
                        <br />
                        <span class="desc">Computation request of uncollected pension.</span>
                        <div class="icon">
                            <img src="/Content/images/dashboard/home.png" alt="Over-remittance List">
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-xl-4 col-md-6 col-12">
                <a href="@Url.Action("AccruedInquiry", "Accrued")">
                    <div class="statistic__item item--blue">
                        <h3 class="counter-value">Accrued Inquiry</h3>
                        <br />
                        <span class="desc">Computed uncollected pension list for approval.<br /> </span>
                        <div class="icon">
                            <img src="/Content/images/dashboard/review.png" alt="For Approval List">
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-xl-4 col-md-6 col-12">
                <a href="@Url.Action("SOD", "Accrued")">
                    <div class="statistic__item item--green">
                        <h3 class="counter-value">SOD Entry (4)</h3>
                        <br />
                        <span class="desc">Create an statement of distribution entry.</span>
                        <div class="icon">
                            <img src="/Content/images/dashboard/bar-chart.png" alt="Over Remittance">
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

<div class="dash-content">
    <div class="container-fluid">
        <div class="row"></div>
    </div>
</div>

@Scripts.Render("~/Scripts/dashboard")

PVAO.Web/Views/Accrued/List.cshtml
@{
    ViewBag.Title = "Accrued List";
}
<div id="accrued-list" class="recent-activity my-listing">
    <div class="act-title">
        <h5><span class="header-text"></span></h5>
        <p>Accrued</p>

        <p class="breadcrumbs">
            <i class="fa fa-link"></i>
            <a href="/Dashboard/Index">Home</a> / <a href="/Accrued/Index">Accrued Option</a> / <span class="subheader-text">Accrued List</span>
        </p>
    </div>
    <div class="row">
        <form class="row hero__form v1 filter listing-filter list-filter">
            <div class="bs-dropdown dropdown show"></div>

            <div class="yr-dropdown dropdown show"></div>

            <div class="mt-dropdown dropdown show"></div>

            <div class="input-search">
                <input id="search-accrued-text" type="text" placeholder="Search accrued here...">
            </div>
        </form>
        <div id="wrapper" class="col-md-12">
            <section>
                <div class="data-container">
                    <table id="accrued-table" class="table table-hover"></table>
                    <center id="no-available-accrueds">
                        <p class="font-italic">
                            <i class="fa fa-exclamation-triangle error-icon" aria-hidden="true"></i> No accrued listed yet.
                        </p>
                    </center>
                </div>
                <div class="row">
                    <div class="col-md-10"></div>
                    <div class="col-md-2">
                        <div id="pagination-accrued"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-7"></div>
                    <div class="col-md-5">
                        <button id="export-excel-button" type="button" class="btn btn-success"><i class="far fa-file-excel"></i> Export to Excel</button>
                        <button id="export-pdf-button" type="button" class="btn btn-danger"><i class="far fa-file-pdf"></i> Export to PDF</button>
                    </div>
                </div>
                <br /><br />
            </section>

            <div class="accrued-pagination"></div>

        </div>
    </div>
</div>
@Scripts.Render("~/Scripts/layout")
@Scripts.Render("~/Scripts/accrued")
@Scripts.Render("~/Scripts/api")
@Scripts.Render("~/Scripts/excelhelper")
@Scripts.Render("~/Scripts/pdfhelper")